# Generated by Django 5.2.8 on 2026-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
