# Generated by Django 6.0.1 on 2026-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_bloqueado_ate_otp_tentativas_otp_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='otp',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
