# Generated by Django 6.0.1 on 2026-02-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_foto_remove_otp_telefone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('BARBEIRO', 'Barbeiro'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
