# Generated by Django 6.0.1 on 2026-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
