# Generated by Django 6.0.1 on 2026-02-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('dono', 'Dono')], default='cliente', max_length=20),
        ),
    ]
