# Generated by Django 6.0.1 on 2026-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_facebook_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anos_experiencia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cortes_feitos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
