# Generated by Django 6.0.1 on 2026-02-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_anos_experiencia_profile_cortes_feitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='especialidade',
            field=models.CharField(blank=True, default='Barbeiro Profissional', max_length=100, null=True),
        ),
    ]
