# Generated by Django 6.0.1 on 2026-02-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_barberphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saldo_devedor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
