# Generated by Django 6.0.1 on 2026-02-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBarbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortes_para_brinde', models.PositiveIntegerField(default=10, verbose_name='Cortes necessários para ganhar brinde')),
                ('mensagem_brinde', models.CharField(default='Parabéns! Você ganhou um brinde 🎉', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
