# Generated by Django 6.0.1 on 2026-02-05 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cortes_necessarios', models.PositiveIntegerField()),
                ('cor', models.CharField(default='#FFD700', max_length=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='configuracaobarbearia',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Brindes'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortes_ganhos', models.PositiveIntegerField(default=0)),
                ('nivel_fidelidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearia.nivelfidelidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
