# Generated by Django 6.0.1 on 2026-02-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_nivelfidelidade'),
        ('barbearia', '0002_nivelfidelidade_alter_configuracaobarbearia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel_fidelidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.nivelfidelidade'),
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cortes_ganhos',
            new_name='cortes_realizados',
        ),
        migrations.DeleteModel(
            name='NivelFidelidade',
        ),
    ]
