# Generated by Django 6.0.1 on 2026-02-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_alter_profile_nivel_fidelidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cortes_realizados',
        ),
    ]
