# Generated by Django 6.0.1 on 2026-02-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_remove_profile_cortes_realizados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaobarbearia',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Brinde'},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
