# Generated by Django 6.0.1 on 2026-02-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0005_alter_configuracaobarbearia_options_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
