# Generated by Django 6.0.1 on 2026-02-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0006_bloqueiodata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloqueioData',
        ),
    ]
