# Generated by Django 6.0.1 on 2026-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('INFO', 'Informação')], default='INFO', max_length=20),
        ),
    ]
