# Generated by Django 6.0.1 on 2026-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='tipo',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('DONO', 'Dono')], default='FUNCIONARIO', max_length=15),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
