# Generated by Django 6.0.1 on 2026-02-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiros', '0002_barbeiro_tipo_alter_barbeiro_comissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='tipo',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='anos_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='cortes_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
