# Generated by Django 6.0.1 on 2026-02-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiros', '0003_remove_barbeiro_ativo_remove_barbeiro_comissao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='anos_experiencia',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='cortes_realizados',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='tipo',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('DONO', 'Dono')], default='FUNCIONARIO', max_length=15),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbeiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
