# Generated by Django 6.0.1 on 2026-02-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiros', '0006_alter_perfilbarbeiro_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilBarbeiro',
        ),
    ]
