# Generated by Django 6.0.1 on 2026-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cortes_necessarios', models.PositiveIntegerField()),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['cortes_necessarios'],
            },
        ),
    ]
