# Generated by Django 6.0.1 on 2026-02-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento'),
        ),
    ]
