# Generated by Django 6.0.1 on 2026-02-09 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_alter_avaliacao_agendamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('barbeiro', 'cliente')},
        ),
    ]
