# Generated by Django 6.0.1 on 2026-02-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_alter_avaliacao_unique_together'),
        ('barbeiros', '0003_remove_barbeiro_ativo_remove_barbeiro_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='barbeiros.barbeiro'),
        ),
    ]
