# Generated by Django 6.0.1 on 2026-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_disponibilidadebarbeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='E_BLOQUEIO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='OBSERVACAO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadebarbeiro',
            name='intervalo_minutos',
            field=models.IntegerField(default=30),
        ),
    ]
