# Generated by Django 6.0.1 on 2026-02-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_agendamento_e_bloqueio_agendamento_observacao_and_more'),
        ('barbeiros', '0004_remove_barbeiro_anos_experiencia_remove_barbeiro_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(choices=[('ALMOCO', 'Horário de Almoço'), ('PARTICULAR', 'Assunto Particular'), ('FOLGA', 'Folga'), ('OUTRO', 'Outro')], default='ALMOCO', max_length=20)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='barbeiros.barbeiro')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
            },
        ),
    ]
